version: '3.8'
services:
  spoolman:
    image: ${GHCR_IMAGE:-donkie/spoolman}:test
    environment:
      - SPOOLMAN_LOGGING_LEVEL=INFO
      - TZ=Europe/Stockholm
  tester:
    image: ${GHCR_IMAGE:-donkie/spoolman}-tester:latest
    volumes:
      - ./tests:/tester/tests
    environment:
      - DB_TYPE=sqlite
    depends_on:
      - spoolman
